apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
      - name: author-service
        image: author-service-image:latest
        ports:
        - containerPort: 50051
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  ports:
    - port: 50051
  selector:
    app: author-service
