apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: book-service-image:latest
        ports:
        - containerPort: 50052
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
        - name: AUTHOR_SERVICE_URL
          value: "author-service:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  ports:
    - port: 50052
  selector:
    app: book-service
